// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1-devel
// 	protoc        (unknown)
// source: hotstufforderer.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HotStuffNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height      int32       `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	View        int32       `protobuf:"varint,2,opt,name=view,proto3" json:"view,omitempty"`
	Parent      []byte      `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"` // The digest of the parent node
	Batch       *Batch      `protobuf:"bytes,4,opt,name=batch,proto3" json:"batch,omitempty"`
	Certificate *HotStuffQC `protobuf:"bytes,5,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Aborted     bool        `protobuf:"varint,6,opt,name=aborted,proto3" json:"aborted,omitempty"`
}

func (x *HotStuffNode) Reset() {
	*x = HotStuffNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hotstufforderer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HotStuffNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotStuffNode) ProtoMessage() {}

func (x *HotStuffNode) ProtoReflect() protoreflect.Message {
	mi := &file_hotstufforderer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotStuffNode.ProtoReflect.Descriptor instead.
func (*HotStuffNode) Descriptor() ([]byte, []int) {
	return file_hotstufforderer_proto_rawDescGZIP(), []int{0}
}

func (x *HotStuffNode) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *HotStuffNode) GetView() int32 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *HotStuffNode) GetParent() []byte {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *HotStuffNode) GetBatch() *Batch {
	if x != nil {
		return x.Batch
	}
	return nil
}

func (x *HotStuffNode) GetCertificate() *HotStuffQC {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *HotStuffNode) GetAborted() bool {
	if x != nil {
		return x.Aborted
	}
	return false
}

// Since we keep a fixed leader for the segment, the vote does not contain a full node, just a reference
type HotStuffVote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height int32       `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Digest []byte      `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	TsQc   *HotStuffQC `protobuf:"bytes,3,opt,name=ts_qc,json=tsQc,proto3" json:"ts_qc,omitempty"`
}

func (x *HotStuffVote) Reset() {
	*x = HotStuffVote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hotstufforderer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HotStuffVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotStuffVote) ProtoMessage() {}

func (x *HotStuffVote) ProtoReflect() protoreflect.Message {
	mi := &file_hotstufforderer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotStuffVote.ProtoReflect.Descriptor instead.
func (*HotStuffVote) Descriptor() ([]byte, []int) {
	return file_hotstufforderer_proto_rawDescGZIP(), []int{1}
}

func (x *HotStuffVote) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *HotStuffVote) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *HotStuffVote) GetTsQc() *HotStuffQC {
	if x != nil {
		return x.TsQc
	}
	return nil
}

type HotStuffQC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height    int32         `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Node      *HotStuffNode `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Signature []byte        `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *HotStuffQC) Reset() {
	*x = HotStuffQC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hotstufforderer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HotStuffQC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotStuffQC) ProtoMessage() {}

func (x *HotStuffQC) ProtoReflect() protoreflect.Message {
	mi := &file_hotstufforderer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotStuffQC.ProtoReflect.Descriptor instead.
func (*HotStuffQC) Descriptor() ([]byte, []int) {
	return file_hotstufforderer_proto_rawDescGZIP(), []int{2}
}

func (x *HotStuffQC) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *HotStuffQC) GetNode() *HotStuffNode {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *HotStuffQC) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type HotStuffProposal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Leader int32         `protobuf:"varint,1,opt,name=leader,proto3" json:"leader,omitempty"`
	Node   *HotStuffNode `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *HotStuffProposal) Reset() {
	*x = HotStuffProposal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hotstufforderer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HotStuffProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotStuffProposal) ProtoMessage() {}

func (x *HotStuffProposal) ProtoReflect() protoreflect.Message {
	mi := &file_hotstufforderer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotStuffProposal.ProtoReflect.Descriptor instead.
func (*HotStuffProposal) Descriptor() ([]byte, []int) {
	return file_hotstufforderer_proto_rawDescGZIP(), []int{3}
}

func (x *HotStuffProposal) GetLeader() int32 {
	if x != nil {
		return x.Leader
	}
	return 0
}

func (x *HotStuffProposal) GetNode() *HotStuffNode {
	if x != nil {
		return x.Node
	}
	return nil
}

type HotStuffNewView struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	View        int32       `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Certificate *HotStuffQC `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`
}

func (x *HotStuffNewView) Reset() {
	*x = HotStuffNewView{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hotstufforderer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HotStuffNewView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotStuffNewView) ProtoMessage() {}

func (x *HotStuffNewView) ProtoReflect() protoreflect.Message {
	mi := &file_hotstufforderer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotStuffNewView.ProtoReflect.Descriptor instead.
func (*HotStuffNewView) Descriptor() ([]byte, []int) {
	return file_hotstufforderer_proto_rawDescGZIP(), []int{4}
}

func (x *HotStuffNewView) GetView() int32 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *HotStuffNewView) GetCertificate() *HotStuffQC {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type HotStuffSendTimestamp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HighTimestamp int32 `protobuf:"varint,1,opt,name=HighTimestamp,json=highTimestamp,proto3" json:"HighTimestamp,omitempty"`
}

func (x *HotStuffSendTimestamp) Reset() {
	*x = HotStuffSendTimestamp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hotstufforderer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HotStuffSendTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotStuffSendTimestamp) ProtoMessage() {}

func (x *HotStuffSendTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_hotstufforderer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotStuffSendTimestamp.ProtoReflect.Descriptor instead.
func (*HotStuffSendTimestamp) Descriptor() ([]byte, []int) {
	return file_hotstufforderer_proto_rawDescGZIP(), []int{5}
}

func (x *HotStuffSendTimestamp) GetHighTimestamp() int32 {
	if x != nil {
		return x.HighTimestamp
	}
	return 0
}

var File_hotstufforderer_proto protoreflect.FileDescriptor

var file_hotstufforderer_proto_rawDesc = []byte{
	0x0a, 0x15, 0x68, 0x6f, 0x74, 0x73, 0x74, 0x75, 0x66, 0x66, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x73, 0x1a, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xcd, 0x01, 0x0a, 0x0c, 0x48, 0x6f, 0x74, 0x53, 0x74, 0x75, 0x66, 0x66, 0x4e, 0x6f,
	0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x69,
	0x65, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x76, 0x69, 0x65, 0x77, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x05, 0x62, 0x61, 0x74, 0x63, 0x68, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x73, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x05, 0x62, 0x61, 0x74, 0x63, 0x68, 0x12, 0x37,
	0x0a, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e,
	0x48, 0x6f, 0x74, 0x53, 0x74, 0x75, 0x66, 0x66, 0x51, 0x43, 0x52, 0x0b, 0x63, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x62, 0x6f, 0x72, 0x74,
	0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x61, 0x62, 0x6f, 0x72, 0x74, 0x65,
	0x64, 0x22, 0x6a, 0x0a, 0x0c, 0x48, 0x6f, 0x74, 0x53, 0x74, 0x75, 0x66, 0x66, 0x56, 0x6f, 0x74,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69, 0x67,
	0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73,
	0x74, 0x12, 0x2a, 0x0a, 0x05, 0x74, 0x73, 0x5f, 0x71, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e, 0x48, 0x6f, 0x74,
	0x53, 0x74, 0x75, 0x66, 0x66, 0x51, 0x43, 0x52, 0x04, 0x74, 0x73, 0x51, 0x63, 0x22, 0x6f, 0x0a,
	0x0a, 0x48, 0x6f, 0x74, 0x53, 0x74, 0x75, 0x66, 0x66, 0x51, 0x43, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x2b, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e, 0x48, 0x6f,
	0x74, 0x53, 0x74, 0x75, 0x66, 0x66, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x57,
	0x0a, 0x10, 0x48, 0x6f, 0x74, 0x53, 0x74, 0x75, 0x66, 0x66, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73,
	0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x04, 0x6e, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x73, 0x2e, 0x48, 0x6f, 0x74, 0x53, 0x74, 0x75, 0x66, 0x66, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x5e, 0x0a, 0x0f, 0x48, 0x6f, 0x74, 0x53, 0x74,
	0x75, 0x66, 0x66, 0x4e, 0x65, 0x77, 0x56, 0x69, 0x65, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x69,
	0x65, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x76, 0x69, 0x65, 0x77, 0x12, 0x37,
	0x0a, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2e,
	0x48, 0x6f, 0x74, 0x53, 0x74, 0x75, 0x66, 0x66, 0x51, 0x43, 0x52, 0x0b, 0x63, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x22, 0x3d, 0x0a, 0x15, 0x48, 0x6f, 0x74, 0x53, 0x74,
	0x75, 0x66, 0x66, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x24, 0x0a, 0x0d, 0x48, 0x69, 0x67, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x68, 0x69, 0x67, 0x68, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hotstufforderer_proto_rawDescOnce sync.Once
	file_hotstufforderer_proto_rawDescData = file_hotstufforderer_proto_rawDesc
)

func file_hotstufforderer_proto_rawDescGZIP() []byte {
	file_hotstufforderer_proto_rawDescOnce.Do(func() {
		file_hotstufforderer_proto_rawDescData = protoimpl.X.CompressGZIP(file_hotstufforderer_proto_rawDescData)
	})
	return file_hotstufforderer_proto_rawDescData
}

var file_hotstufforderer_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_hotstufforderer_proto_goTypes = []interface{}{
	(*HotStuffNode)(nil),          // 0: protobufs.HotStuffNode
	(*HotStuffVote)(nil),          // 1: protobufs.HotStuffVote
	(*HotStuffQC)(nil),            // 2: protobufs.HotStuffQC
	(*HotStuffProposal)(nil),      // 3: protobufs.HotStuffProposal
	(*HotStuffNewView)(nil),       // 4: protobufs.HotStuffNewView
	(*HotStuffSendTimestamp)(nil), // 5: protobufs.HotStuffSendTimestamp
	(*Batch)(nil),                 // 6: protobufs.Batch
}
var file_hotstufforderer_proto_depIdxs = []int32{
	6, // 0: protobufs.HotStuffNode.batch:type_name -> protobufs.Batch
	2, // 1: protobufs.HotStuffNode.certificate:type_name -> protobufs.HotStuffQC
	2, // 2: protobufs.HotStuffVote.ts_qc:type_name -> protobufs.HotStuffQC
	0, // 3: protobufs.HotStuffQC.node:type_name -> protobufs.HotStuffNode
	0, // 4: protobufs.HotStuffProposal.node:type_name -> protobufs.HotStuffNode
	2, // 5: protobufs.HotStuffNewView.certificate:type_name -> protobufs.HotStuffQC
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_hotstufforderer_proto_init() }
func file_hotstufforderer_proto_init() {
	if File_hotstufforderer_proto != nil {
		return
	}
	file_request_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_hotstufforderer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HotStuffNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hotstufforderer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HotStuffVote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hotstufforderer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HotStuffQC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hotstufforderer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HotStuffProposal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hotstufforderer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HotStuffNewView); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hotstufforderer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HotStuffSendTimestamp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hotstufforderer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hotstufforderer_proto_goTypes,
		DependencyIndexes: file_hotstufforderer_proto_depIdxs,
		MessageInfos:      file_hotstufforderer_proto_msgTypes,
	}.Build()
	File_hotstufforderer_proto = out.File
	file_hotstufforderer_proto_rawDesc = nil
	file_hotstufforderer_proto_goTypes = nil
	file_hotstufforderer_proto_depIdxs = nil
}
